import {
  Banknote,
  BarChart3,
  CalendarClock,
  CalendarDays,
  CircleDollarSign,
  Factory,
  FileSearch,
  FolderTree,
  Handshake,
  Landmark,
  LineChart,
  Link2,
  List,
  PackageSearch,
  Percent,
  PieChart,
  Receipt,
  Scale,
  Settings,
  Store,
  Tags,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";
import type { AdmIconId } from "@/lib/administracionNav";

export const ADM_ICON_MAP: Record<AdmIconId, LucideIcon> = {
  landmark: Landmark,
  handshake: Handshake,
  "bar-chart-3": BarChart3,
  factory: Factory,
  settings: Settings,
  store: Store,
  scale: Scale,
  receipt: Receipt,
  "folder-tree": FolderTree,
  "circle-dollar": CircleDollarSign,
  banknote: Banknote,
  percent: Percent,
  "calendar-days": CalendarDays,
  wallet: Wallet,
  "calendar-clock": CalendarClock,
  "file-search": FileSearch,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  list: List,
  "link-2": Link2,
  "package-search": PackageSearch,
  tags: Tags,
  users: Users,
};
